### PR TITLE
Numerous changes

### PR DESCRIPTION
**Pull request by SausageMcSauce**
I fixed spelling mistakes, indented many code in files for readability, made the favicon able to show up and did several more things.

This has been tested by me on an online IDE called repl.it (this is why a .replit file is in the gitignore).

### CODE REVIEW

**Comment by LankyBox01** [comment]
Sure, i'll take it.

**Comment by LankyBox01** [comment]
Shall i add your name to the credits?

**Comment by LankyBox01** [comment]
I was also wondering why you forked the repository XD

**Comment by aboutDavid** [comment]
Usually to make multiple changes, you would fork a repository.

**Comment by LankyBox01** [comment]
I know, lol

**Pull request merged**
