### PR TITLE
add home page because you asked for one

### PR DESCRIPTION
**Pull request by frappepancake**

### CODE REVIEW

**Review by aboutDavid — CHANGES_REQUESTED** [review]
Can you prettify this code please?

**Comment by aboutDavid** [comment]
* a.k.a format the code.

**Comment by frappepancake** [comment]
ok

**Comment by aboutDavid** [comment]
Ok, thanks!

**Comment by LankyBox01** [comment]
Before anyone merges this, i'll check it. Please wait 2-4 hours after all my checks pass

**Comment by aboutDavid** [comment]
Why did you close it? You can leave it open...

**Comment by LankyBox01** [comment]
Someone could accidentally merge it.

**Comment by LankyBox01** [comment]
I'm not sure this would fit the theme, where should the videos show up? And how could this be the homepage? I'll optimize it and test it later. In the meantime **DO NOT MERGE IT; NOR RE-OPEN IT**

**Comment by BibliotecaOvidiu** [comment]
So, i analyzed it and i saw that you used a code by RiversideRocks to make the website -- no, denied.

**Comment by LankyBox01** [comment]
Approved.

**Comment by frappepancake** [comment]
> So, i analyzed it and i saw that you used a code by RiversideRocks to make the website -- no, denied.

I had permission?

**Comment by LankyBox01** [comment]
I know, you used a website generator. And we don't use these here!

**Comment by frappepancake** [comment]
> I know, you used a website generator. And we don't use these here!

ok srry

**Comment by LankyBox01** [comment]
It's ok, keep making creative pull requests!

**Comment by aboutDavid** [comment]
Oh yeah, I see the website builder:
https://github.com/RiversideRocks/BuildAHomePage

**Pull request closed without merging**
